version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - app_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s

  flask_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - FLASK_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app_network
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

volumes:
  redis_data:

networks:
  app_network:
